Apply tx metadata for 1-queue TSN
tsnlab/2023-krri-tci-xdma pull request #11
Opened 2024-05-22 06:28 UTC by pooky1004

XDMA Network driver에 1-queue TSN용 tx metadata 적용

2024-05-28 00:46 UTC, tribela commented on XDMA/linux-kernel/xdma/xdma_netdev.c
> +#endif
```suggestion
#endif // DEBUG_ONE_QUEUE_TSN_
```

2024-05-28 00:48 UTC, tribela commented on XDMA/linux-kernel/xdma/xdma_netdev.h
> +#define _DEFAULT_TO_MARGIN_ (19100)
Please comment that what unit this value uses
eg:
```c
#define _DEFAULT_FROM_MARGIN_ (500)  // ns
```
Also, Is it really need surrounding underscores?

2024-05-28 00:49 UTC, tribela commented on XDMA/linux-kernel/xdma/xdma_netdev.h
> +        uint8_t fail_policy;
We need enum value for fail policy

2024-05-28 00:50 UTC, tribela commented on XDMA/linux-kernel/xdma/xdma_netdev.c
> +void dump_buffer(unsigned char* buffer, int len)
`len` is not used

2024-05-28 00:51 UTC, tribela requested changes
Some comment is required. And need some changes

2024-05-28 00:59 UTC, tribela commented on XDMA/linux-kernel/xdma/xdma_netdev.c
> +        pr_err("\n");
```suggestion
        char pbuffer[16 * 3];
        int i = 0;
        pr_err("[Buffer]");
        while (i < len) {
                int j = 0;
                memset(pbuffer, 0, sizeof(pbuffer));
                while (j < 16) {
                        if (i + j >= len) {
                                break;
                        }
                        sprintf(pbuffer + (j * 3), "%02x ", buffer[i + j] & 0xFF);
                        j++;
                }
                pr_err("%s", pbuffer);
                i += 16;
        }

        pr_err("\n");
```

2024-05-28 01:01 UTC, tribela commented on XDMA/linux-kernel/xdma/xdma_netdev.c
> +#endif
Commenting on `#endif` improves readability (especially when nesting `#if` statements)

2024-05-28 02:43 UTC, tribela commented on XDMA/linux-kernel/xdma/xdma_netdev.c
> +        sys_count_low = (uint32_t)(ioread32(xdev->bar[0] + 0x0384) & 0x1FFFFFFF);
What is magic number`0x0384` for?
Please make it named literal value

2024-06-03 03:41 UTC, pooky1004 commented on XDMA/linux-kernel/xdma/xdma_netdev.c
> +#endif
적용 했습니다.

2024-06-03 03:42 UTC, pooky1004 commented on XDMA/linux-kernel/xdma/xdma_netdev.h
> +#define _DEFAULT_TO_MARGIN_ (19100)
rick count 값이고 주석으로 단위가 어떻게 되는지 달았습니다.

2024-06-03 03:43 UTC, pooky1004 commented on XDMA/linux-kernel/xdma/xdma_netdev.h
> +        uint8_t fail_policy;
enum e_fail_policy 로 정의했습니다.

2024-06-03 03:45 UTC, pooky1004 commented on XDMA/linux-kernel/xdma/xdma_netdev.c
> +        pr_err("\n");
제안해 주신대로 변경했습니다.

2024-06-03 03:46 UTC, pooky1004 commented on XDMA/linux-kernel/xdma/xdma_netdev.c
> +        sys_count_low = (uint32_t)(ioread32(xdev->bar[0] + 0x0384) & 0x1FFFFFFF);
레지스터 이름을 헤더 파일에 정의 후 사용하는 것으로 변경했습니다.

2024-06-03 04:09 UTC, tribela commented on XDMA/linux-kernel/xdma/xdma_netdev.h
> +    delay_allowed = 1,
예전에 이 둘 이름을 drop, retry로 정의했을거예요.

2024-06-03 04:09 UTC, tribela commented on XDMA/linux-kernel/xdma/xdma_netdev.h
> +#define TX_METADATA_SIZE 32
Don't.

Please use `sizeof(struct tx_metadata)`

2024-06-03 05:34 UTC, pooky1004 commented on XDMA/linux-kernel/xdma/xdma_netdev.h
> +    delay_allowed = 1,
policy_drop = 0,
policy_retry = 1,
으로 변경했습니다.

2024-06-03 05:35 UTC, pooky1004 commented on XDMA/linux-kernel/xdma/xdma_netdev.h
> +#define TX_METADATA_SIZE 32
#define TX_METADATA_SIZE (sizeof(struct tx_metadata)) 이렇게 변경했습니다.

2024-06-10 23:59 UTC, closed without merging

2024-06-10 23:59 UTC, tribela commented
This PR is merged via #12. Closing this.